import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function dataModule(relativePath, replacements = {}) {
  let source = readFileSync(new URL(relativePath, import.meta.url), "utf8");
  for (const [from, to] of Object.entries(replacements)) {
    source = source.replaceAll(from, to);
  }
  return "data:text/javascript;base64," + Buffer.from(source).toString("base64");
}

const metadataUrl = dataModule("../web/js/aio/jpeg_workflow_metadata.js");
const metadataModule = await import(metadataUrl);
const importModule = await import(dataModule(
  "../web/js/aio/jpeg_workflow_import.js",
  { "./jpeg_workflow_metadata.js": metadataUrl },
));

assert.deepEqual(
  Object.keys(metadataModule).sort(),
  [
    "AIO_JPEG_METADATA_LIMITS",
    "aioIsJpegFile",
    "aioParseNativeJpegMetadata",
    "aioReadNativeJpegMetadata",
  ],
);
assert.deepEqual(
  Object.keys(importModule).sort(),
  ["aioHostSupportsNativeJpegMetadata", "aioInstallJpegWorkflowImport"],
);

// Generated by Pillow from easyuse_anima.aio.native_image_output._build_exif_bytes.
const WORKFLOW_JPEG = Buffer.from(
  "/9j/4AAQSkZJRgABAQAAAQABAAD/4QDIRXhpZgAATU0AKgAAAAgAAwEPAAIAAAAyAAAAMgEQAAIAAAAzAAAAZIdpAAQAAAABAAAAmAAAAAB3b3JrZmxvdzp7Imxhc3Rfbm9kZV9pZCI6MSwibm9kZXMiOltdLCJsaW5rcyI6W119AHByb21wdDp7IjEiOnsiY2xhc3NfdHlwZSI6IktTYW1wbGVyIiwiaW5wdXRzIjp7fX19AAAAAZKGAAEAAAAWAAAAqgAAAABVTklDT0RFAABzAGUAZQBkADoAIAAx/9sAQwAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ0NB8nOT04MjwuMzQy/9sAQwEJCQkMCwwYDQ0YMiEcITIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy/8AAEQgAAQABAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A9/ooooA//9k=",
  "base64",
);
const PROMPT_JPEG = Buffer.from(
  "/9j/4AAQSkZJRgABAQAAAQABAAD/4QCKRXhpZgAATU0AKgAAAAgAAgEQAAIAAAAzAAAAJodpAAQAAAABAAAAWgAAAABwcm9tcHQ6eyIxIjp7ImNsYXNzX3R5cGUiOiJLU2FtcGxlciIsImlucHV0cyI6e319fQAAAAGShgABAAAAFgAAAGwAAAAAVU5JQ09ERQAAcwBlAGUAZAA6ACAAMf/bAEMACAYGBwYFCAcHBwkJCAoMFA0MCwsMGRITDxQdGh8eHRocHCAkLicgIiwjHBwoNyksMDE0NDQfJzk9ODI8LjM0Mv/bAEMBCQkJDAsMGA0NGDIhHCEyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMv/AABEIAAEAAQMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APf6KKKAP//Z",
  "base64",
);

function exactArrayBuffer(bytes) {
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}

function jpegFile(bytes, { name = "native-output.jpeg", type = "image/jpeg" } = {}) {
  const slices = [];
  return {
    name,
    type,
    size: bytes.byteLength,
    slices,
    slice(start, end) {
      slices.push([start, end]);
      const value = bytes.subarray(start, end);
      return { arrayBuffer: async () => exactArrayBuffer(value) };
    },
  };
}

const expectedWorkflow = { last_node_id: 1, nodes: [], links: [] };
const expectedPrompt = { 1: { class_type: "KSampler", inputs: {} } };
const parsed = metadataModule.aioParseNativeJpegMetadata(WORKFLOW_JPEG);
assert.deepEqual(parsed, { workflow: expectedWorkflow, prompt: expectedPrompt });

const malformedWorkflow = Buffer.from(WORKFLOW_JPEG);
const workflowPrefix = Buffer.from("workflow:{", "utf8");
const workflowOffset = malformedWorkflow.indexOf(workflowPrefix);
assert.ok(workflowOffset > 0);
malformedWorkflow[workflowOffset + workflowPrefix.byteLength - 1] = "!".charCodeAt(0);
assert.deepEqual(
  metadataModule.aioParseNativeJpegMetadata(malformedWorkflow),
  { workflow: undefined, prompt: expectedPrompt },
  "malformed workflow JSON must retain the valid prompt fallback",
);

const readFile = jpegFile(WORKFLOW_JPEG);
assert.deepEqual(
  await metadataModule.aioReadNativeJpegMetadata(readFile),
  { workflow: expectedWorkflow, prompt: expectedPrompt },
);
assert.deepEqual(readFile.slices, [[0, WORKFLOW_JPEG.byteLength]]);

const largeFile = jpegFile(WORKFLOW_JPEG);
largeFile.size = 1024 * 1024 * 1024;
await metadataModule.aioReadNativeJpegMetadata(largeFile);
assert.deepEqual(
  largeFile.slices,
  [[0, metadataModule.AIO_JPEG_METADATA_LIMITS.scanBytes]],
  "large images must read only the bounded metadata prefix",
);

const graphCalls = [];
const promptCalls = [];
const delegated = [];
const app = {
  handleFile(...args) {
    delegated.push({ receiver: this, args });
    return "delegated";
  },
  async loadGraphData(...args) {
    graphCalls.push({ receiver: this, args });
    return "graph-loaded";
  },
  async loadApiJson(...args) {
    promptCalls.push({ receiver: this, args });
    return "prompt-loaded";
  },
};
assert.equal(
  importModule.aioInstallJpegWorkflowImport(app, { globalObject: {} }),
  true,
);
const installedHandler = app.handleFile;
assert.equal(
  importModule.aioInstallJpegWorkflowImport(app, { globalObject: {} }),
  false,
  "installation must be idempotent",
);
assert.equal(app.handleFile, installedHandler);
assert.equal(
  await app.handleFile(
    jpegFile(WORKFLOW_JPEG, { name: "round.trip.jpeg" }),
    "file_drop",
    { deferWarnings: true },
  ),
  "graph-loaded",
);
assert.equal(delegated.length, 0);
assert.equal(promptCalls.length, 0, "workflow must take priority over prompt");
assert.equal(graphCalls.length, 1);
assert.equal(graphCalls[0].receiver, app);
assert.deepEqual(graphCalls[0].args, [
  expectedWorkflow,
  true,
  true,
  "round.trip",
  { openSource: "file_drop", deferWarnings: true },
]);

const graphFailureWarnings = [];
let graphFailureDelegations = 0;
let graphFailurePromptLoads = 0;
const graphFailureApp = {
  handleFile() {
    graphFailureDelegations += 1;
    return "must-not-delegate";
  },
  loadGraphData() {
    return Promise.reject(new Error("invalid workflow structure"));
  },
  loadApiJson() {
    graphFailurePromptLoads += 1;
    return "prompt-after-workflow-failure";
  },
};
assert.equal(importModule.aioInstallJpegWorkflowImport(graphFailureApp, {
  globalObject: {},
  async readMetadata() {
    return {
      workflow: { nodes: "invalid" },
      prompt: expectedPrompt,
    };
  },
  logger: {
    warn(...args) {
      graphFailureWarnings.push(args);
    },
  },
}), true);
assert.equal(
  await graphFailureApp.handleFile(jpegFile(WORKFLOW_JPEG)),
  "prompt-after-workflow-failure",
);
assert.equal(graphFailurePromptLoads, 1);
assert.equal(graphFailureDelegations, 0);
assert.equal(graphFailureWarnings.length, 1);

const promptOnlyCalls = [];
const promptOnlyApp = {
  handleFile() {
    throw new Error("prompt JPEG must not delegate");
  },
  async loadApiJson(...args) {
    promptOnlyCalls.push({ receiver: this, args });
    return "prompt-loaded";
  },
};
assert.equal(
  importModule.aioInstallJpegWorkflowImport(promptOnlyApp, { globalObject: {} }),
  true,
);
assert.equal(
  await promptOnlyApp.handleFile(jpegFile(PROMPT_JPEG, { name: "api.jpg" })),
  "prompt-loaded",
);
assert.equal(promptOnlyCalls[0].receiver, promptOnlyApp);
assert.deepEqual(promptOnlyCalls[0].args, [
  expectedPrompt,
  "api",
  { deferWarnings: undefined },
]);

const promptFailureDelegations = [];
const promptFailureWarnings = [];
const promptFailureApp = {
  handleFile(...args) {
    promptFailureDelegations.push({ receiver: this, args });
    return "prompt-failure-delegated";
  },
};
assert.equal(importModule.aioInstallJpegWorkflowImport(promptFailureApp, {
  globalObject: {},
  async readMetadata() {
    return { prompt: expectedPrompt };
  },
  logger: {
    warn(...args) {
      promptFailureWarnings.push(args);
    },
  },
}), true);
const promptFailureReceiver = {
  loadApiJson() {
    throw new Error("API loader failed synchronously");
  },
};
const promptFailureFile = jpegFile(PROMPT_JPEG);
const promptFailureOptions = { deferWarnings: true, marker: "same-object" };
assert.equal(
  await promptFailureApp.handleFile.call(
    promptFailureReceiver,
    promptFailureFile,
    "file_drop",
    promptFailureOptions,
  ),
  "prompt-failure-delegated",
);
assert.equal(promptFailureWarnings.length, 1);
assert.equal(promptFailureDelegations.length, 1);
assert.equal(promptFailureDelegations[0].receiver, promptFailureReceiver);
assert.deepEqual(promptFailureDelegations[0].args, [
  promptFailureFile,
  "file_drop",
  promptFailureOptions,
]);

const invalidPrompts = [
  {},
  { 1: { inputs: {} } },
  { 1: { class_type: 7, inputs: {} } },
  { 1: { class_type: "KSampler" } },
  { 1: { class_type: "KSampler", inputs: [] } },
];
let invalidPromptDelegations = 0;
let invalidPromptIndex = 0;
const invalidPromptApp = {
  handleFile() {
    invalidPromptDelegations += 1;
    return "invalid-prompt-delegated";
  },
  loadApiJson() {
    throw new Error("structurally invalid API prompts must not reach the loader");
  },
};
assert.equal(importModule.aioInstallJpegWorkflowImport(invalidPromptApp, {
  globalObject: {},
  async readMetadata() {
    const prompt = invalidPrompts[invalidPromptIndex];
    invalidPromptIndex += 1;
    return { prompt };
  },
}), true);
for (const prompt of invalidPrompts) {
  assert.equal(
    await invalidPromptApp.handleFile(jpegFile(PROMPT_JPEG)),
    "invalid-prompt-delegated",
    `invalid prompt must delegate: ${JSON.stringify(prompt)}`,
  );
}
assert.equal(invalidPromptDelegations, invalidPrompts.length);

const delegatedApp = {
  handleFile(...args) {
    delegated.push({ receiver: this, args });
    return "fallback";
  },
  loadGraphData() {
    throw new Error("malformed metadata must not load a graph");
  },
};
assert.equal(
  importModule.aioInstallJpegWorkflowImport(delegatedApp, { globalObject: {} }),
  true,
);
const customReceiver = { marker: "receiver" };
const malformedJpeg = jpegFile(Buffer.from([0xff, 0xd8, 0xff, 0xd9]));
const fallbackOptions = { deferWarnings: false, marker: "same-object" };
assert.equal(
  await delegatedApp.handleFile.call(
    customReceiver,
    malformedJpeg,
    "file_button",
    fallbackOptions,
  ),
  "fallback",
);
const lastDelegation = delegated.at(-1);
assert.equal(lastDelegation.receiver, customReceiver);
assert.deepEqual(lastDelegation.args, [malformedJpeg, "file_button", fallbackOptions]);

let nonJpegReads = 0;
const mediaDelegations = [];
const mediaApp = {
  handleFile(file) {
    mediaDelegations.push(file);
    return file.type;
  },
};
assert.equal(importModule.aioInstallJpegWorkflowImport(mediaApp, {
  globalObject: {},
  async readMetadata() {
    nonJpegReads += 1;
    return undefined;
  },
}), true);
for (const type of ["image/png", "image/webp"]) {
  const file = jpegFile(Buffer.from([1, 2, 3]), { name: `image.${type.slice(6)}`, type });
  assert.equal(await mediaApp.handleFile(file), type);
}
assert.equal(nonJpegReads, 0, "PNG/WebP must not enter the JPEG reader");
assert.deepEqual(mediaDelegations.map((file) => file.type), ["image/png", "image/webp"]);

const nativeHandler = function nativeHandler() {};
const nativeApp = { handleFile: nativeHandler };
const nativeGlobal = { comfyAPI: { pnginfo: { getJpegMetadata() {} } } };
assert.equal(
  importModule.aioInstallJpegWorkflowImport(nativeApp, { globalObject: nativeGlobal }),
  false,
);
assert.equal(nativeApp.handleFile, nativeHandler);

let lateReads = 0;
let lateDelegations = 0;
const lateGlobal = {};
const lateApp = {
  handleFile() {
    lateDelegations += 1;
    return "native-delegated";
  },
};
assert.equal(importModule.aioInstallJpegWorkflowImport(lateApp, {
  globalObject: lateGlobal,
  async readMetadata() {
    lateReads += 1;
    return { workflow: expectedWorkflow };
  },
}), true);
lateGlobal.comfyAPI = { pnginfo: { getJpegMetadata() {} } };
assert.equal(await lateApp.handleFile(jpegFile(WORKFLOW_JPEG)), "native-delegated");
assert.equal(lateReads, 0);
assert.equal(lateDelegations, 1);

const oversizedRead = {
  name: "oversized.jpeg",
  type: "image/jpeg",
  size: 1,
  slice() {
    return {
      async arrayBuffer() {
        return new ArrayBuffer(metadataModule.AIO_JPEG_METADATA_LIMITS.scanBytes + 1);
      },
    };
  },
};
assert.equal(await metadataModule.aioReadNativeJpegMetadata(oversizedRead), undefined);

const invalidIfd = Buffer.from(WORKFLOW_JPEG);
const exifOffset = invalidIfd.indexOf(Buffer.from("Exif\0\0", "binary"));
assert.ok(exifOffset > 0);
const tiffOffset = exifOffset + 6;
const littleEndian = invalidIfd[tiffOffset] === 0x49;
const tiffView = new DataView(
  invalidIfd.buffer,
  invalidIfd.byteOffset + tiffOffset,
  invalidIfd.byteLength - tiffOffset,
);
const firstIfd = tiffView.getUint32(4, littleEndian);
tiffView.setUint16(firstIfd, metadataModule.AIO_JPEG_METADATA_LIMITS.ifdEntries + 1, littleEndian);
assert.equal(metadataModule.aioParseNativeJpegMetadata(invalidIfd), undefined);

const entrySource = readFileSync(
  new URL("../web/js/easyuse_anima_aio.js", import.meta.url),
  "utf8",
);
assert.match(entrySource, /from "\.\/aio\/jpeg_workflow_import\.js"/);
assert.match(entrySource, /installJpegWorkflowImport\(\) \{/);
assert.equal(entrySource.match(/app\.registerExtension\(/g)?.length, 1);

console.log("AiO JPEG workflow import smoke passed.");
